### Create a Product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "yam",
  "description": "Latest local yam with tuber features",
  "price": 699.99,
  "stock": 100
}
